fileRepositoryFolder: C:\Users\aless\OneDrive\Desktop\Live-coding\Media\uploadedFiles
spring:
  datasource:
    url: jdbc:h2:mem:media
    username: Ale
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true